



export const modelsData = [

    {
        id: "model-3",
        name: "Model 3",
        price: "39,940",
        autonomy: "267",
        topSpeed: "140",
        imageBg: "assets/model-3-bg.jpg",
        imageBgMobile: "assets/model-3-bg-m.jpg",
        imageShop: "assets/model-3-shop.jpg",
        category: "1-1-model",
    },
    {
        id: "model-y",
        name: "Model Y",
        price: "53,940",
        autonomy: "318",
        topSpeed: "135",
        imageBg: "assets/model-y-bg.jpg",
        imageBgMobile: "assets/model-y-bg-m.jpg",
        imageShop: "assets/model-3-shop.jpg",
        category: "1-1-model",
    },
    {
        id: "model-s",
        name: "Model S",
        price: "88,740",
        autonomy: "375",
        topSpeed: "155",
        imageBg: "assets/model-s-bg.jpg",
        imageBgMobile: "assets/model-s-bg-m.jpg",
        imageShop: "assets/model-3-shop.jpg",
        category: "1-1-model",
    },
    {
        id: "model-x",
        name: "Model X",
        price: "98,940",
        autonomy: "332",
        topSpeed: "155",
        imageBg: "assets/model-x-bg.jpg",
        imageBgMobile: "assets/model-x-bg-m.jpg",
        imageShop: "assets/model-3-shop.jpg",
        category: "1-1-model",
    },
    {
        id: "solar-panels",
        name: "Solar Panels",
        imageBg: "assets/solar-panel-bg.jpg",
        imageBgMobile: "assets/solar-panel-bg-m.jpg",
        category: "1-1-model",
    },
    {
        id: "solar-roof",
        name: "Solar Roof",
        imageBg: "assets/solar-roof-bg.jpg",
        imageBgMobile: "assets/solar-roof-bg-m.jpg",
        category: "1-1-model",
    },
    {
        id: "accessories",
        name: "Accessories",
        imageBg: "assets/acessories-bg.jpg",
        imageBgMobile: "assets/acessories-bg-m.jpg",
        category: "1-1-model",
    },
]



export const sideMenuData = [

    {
        id: "existing-inventory",
        name: "Existing Inventory",
        url: "#",
        screen: "pc",
        category: "1-sale",
    },
    {
        id: "used-inventory",
        name: "Used Inventory",
        url: "#",
        screen: "pc",
        category: "1-sale",
    },
    {
        id: "trade-in",
        name: "Trade-In",
        url: "#",
        screen: "pc",
        category: "1-sale",
    },
    {
        id: "test-drive",
        name: "Test Drive",
        url: "#",
        screen: "pc",
        category: "1-sale",
    },
    {
        id: "powerwall",
        name: "Powerwall",
        url: "#",
        screen: "pc",
        category: "2-energy",
    },
    {
        id: "commercial-energy",
        name: "Commercial Energy",
        url: "#",
        screen: "pc",
        category: "2-energy",
    },
    {
        id: "utilities",
        name: "Utilities",
        url: "#",
        screen: "pc",
        category: "2-energy",
    },
    {
        id: "charging",
        name: "Charging",
        url: "#",
        screen: "pc",
        category: "2-energy",
    },
    {
        id: "find-us",
        name: "Find Us",
        url: "#",
        screen: "pc",
        category: "3-user",
    },
    {
        id: "support",
        name: "Support",
        url: "#",
        screen: "pc",
        category: "3-user",
    },
    {
        id: "investor-relations",
        name: "Investor Relations",
        url: "#",
        screen: "pc",
        category: "3-user",
    },
    {
        id: "shop",
        name: "Shop",
        url: "#",
        screen: "mobile",
        category: "3-user",
    },
    {
        id: "account",
        name: "Account",
        url: "#",
        screen: "mobile",
        category: "3-user",
    },
    {
        id: "cybertruck",
        name: "Cybertruck",
        url: "#",
        screen: "pc",
        category: "4-others",
    },
    {
        id: "roadster",
        name: "Roadster",
        url: "#",
        screen: "pc",
        category: "4-others",
    },
    {
        id: "semi",
        name: "Semi",
        url: "#",
        screen: "pc",
        category: "4-others",
    },
    {
        id: "news",
        name: "News",
        url: "#",
        screen: "mobile",
        category: "4-others",
    },

]